# Generated by Django 5.2.7 on 2025-10-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.TextField(max_length=35)),
                ('match_date', models.DateField()),
                ('kick_off', models.TimeField()),
                ('home_team_gender', models.TextField(max_length=10)),
                ('home_score', models.IntegerField()),
                ('visiting_score', models.IntegerField()),
                ('match_status', models.TextField(max_length=20)),
            ],
        ),
    ]
